name: cep
version: 1.0.0
description: Uma biblioteca para consulta de CEP.
homepage: https://github.com/tefferson/cep
documentation: https://github.com/tefferson/cep
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  via_cep: ^1.0.6
