name: cep
version: 1.0.0
description: teff
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  via_cep: ^1.0.6
